shell.app.execdblp.dashboard = ( function (my) {

  my._applyStyles = function () {

    // remove the 'old' style
    $("#CSS_JBI_SKELETON").remove();
    $("[data-group='LAYOUT']").remove();


    var configStyle = getConfigStyle(),
      summaryConfig = (configStyle && configStyle["summary"]) ? configStyle["summary"] : {},
      trendConfig = (configStyle && configStyle["trend"]) ? configStyle["trend"] : {},
      reportConfig = (configStyle && configStyle["report"]) ? configStyle["report"] : {};

    var filtersWidthPixels = (summaryConfig["FiltersWidthPixels"] === undefined)
      ? '260'
      : summaryConfig["FiltersWidthPixels"];

    var fontFamily = (configStyle && configStyle["dashboard"] && configStyle["dashboard"]["FontFamily"]) || "Verdana";

    var s = "";
//@formatter:off
    s += "<style type='text/css' id='CSS_JBI_SKELETON' data-repstyle='execdblp'>"
      + "svg{"
      + "overflow:visible !important;"
      + "}"
      + ".highcharts-container{"
      + "overflow:visible !important;"
      + "position: inherit !important;"
      + "}"
      + ".highcharts-stack-labels>text {"
      + "visibility: visible!important;"
      + "}"
      + ".highcharts-container>svg{"
      + "position: absolute;"
      + "}"
      + ".highcharts-tooltip {"
      + "z-index: 9998;"
      + "}"
      + "#jbi_container{"
      + "position: fixed;"
      + "top: 0;"
      + "left: 0;"
      + "right: 0;"
      + "height: 100%;"
      + "background-color : white;"
      + "overflow: auto;"
      + "}"
      + "#jbi_app{"
      + "margin-left: auto;"
      + "margin-right: auto;"
      + "max-width: 1200px;"
      + "min-width: 400px;"
      + "position: relative;"
      + "display: block;"
      + "min-height: 100px;"
      + "height: 100%;"
      + "top: 0;"
      + "left: 0;"
      + "right: 0;"
      + "border-left : 1px solid #e5e5e5;"
      + "border-right : 1px solid #e5e5e5;"
      + "z-index: 12000;"
      + "}"

        // Static summary section
      + "#jbi_summary{"
      + "position: absolute;"
      + "display: block;"
      + "left: 0;"
      + "right: 0;"
      + "top: 0;"
      + "pointer-events: none;"
      + "}";

    s += "#jbi_summary_filter{"
      + "position: relative;"
      + "display: block;"
      + "left: 0;"
      + "right: 0;"
      + "height:" + summaryConfig["FiltersHeightPixels"] + "px;"
      + "background-color: white;"
      + "}"
      + "#jbi_summary_filter_business{"
      + "margin-left: auto;"
      + "margin-right: auto;"
      + "line-height: 34px;"
      + "text-align: center;"
      + "font-family: " + fontFamily + ";"
      + "font-weight: bold;"
      + "font-size: 12px;"
      + "color: #4A4A4A;"
      + "width: " + filtersWidthPixels + "px;"
      + "border: 1px solid lightgrey !important;"
      + "border-top: 0 !important;"
      + "white-space: nowrap;"
      + "box-sizing: border-box;"
      + "pointer-events: initial;"
      + "}";

    if (!my.isMobile) {
      s += "#jbi_summary_filter_business:hover{"
        + "background-color: #EFEFEF;"
        + "-webkit-transition: background-color 200ms ease-in-out;"
        + "-moz-transition: background-color 200ms ease-in-out;"
        + "-o-transition: background-color 200ms ease-in-out;"
        + "transition: background-color 200ms ease-in-out;"
        + "}";
    }


    if (my.isMobile) {
      s += "body {"
    } else {
      s += ".noselect {"
    }
    s += "-webkit-touch-callout: none;"
      + "-webkit-user-select: none;"
      + "-khtml-user-select: none;"
      + "-moz-user-select: none;"
      + "-ms-user-select: none;"
      + "user-select: none;"
      + "}"

      + "#jbi_summary_kpi{"
      + "position: relative;"
      + "display: block;"
      + "height: " + summaryConfig["KpiHeightPixels"] + "px;"
      + "left: 0;"
      + "right: 0;"
      + "font-size: 0px;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi{"
      + "position: relative;"
      + "width: 25%;"
      + "height:" + summaryConfig["KpiHeightPixels"] + "px;"
      + "display: inline-block;"
      + "}"
      + ".jbi_summary_kpi_item{"
      + "position: absolute;"
      + "top: 0;"
      + "bottom: 0;"
      + "left: 0;"
      + "right: 0;"
      + "border-top: 1px solid #e5e5e5;"
      + "border-bottom: 1px solid #e5e5e5;"
      + "}"
      + "#jbi_summary_chart{"
      + "position: relative;"
      + "display: block;"
      + "height: " + summaryConfig["ChartHeightPixels"] + "px;"
      + "left: 0;"
      + "right: 0;"
      + "font-size: 0px;"
      + "}"
      + ".jbi_summary_kpi_item {"
      + "border-left: 1px solid #e5e5e5;"
      + "}"
      + "#jbi_summary_chart .jbi_summary_chart{"
      + "position: relative;"
      + "width: 25%;"
      + "height:" + summaryConfig["ChartHeightPixels"] + "px;"
      + "display: inline-block;"
      + "}"
      + "#jbi_summary_chart .jbi_summary_chart_item{"
      + "position: absolute;"
      + "top: 0;"
      + "bottom: 0;"
      + "left: 0;"
      + "right: 0;"
      + "}"
      + "#jbi_summary_chart_2Content,"
      + "#jbi_summary_chart_3Content,"
      + "#jbi_summary_chart_4Content{"
      + "border-left: 1px solid #e5e5e5;"
      + "box-sizing: border-box;"
      + "}"
      + "#jbi_summary_legend{"
      + "position: relative;"
      + "display: block;"
      + "height: " + ( summaryConfig["LegendHeightPixels"] + 30 ) + "px;";
    if (my.isMobile) {
      s += "margin-top: -8px;"
    }
    s += "width:100%;"
      + "font-size: 0px;"
      + "border-bottom: 1px solid #e5e5e5;"
      + "}"
      + ".jbi_summary_legend_item{"
      + "box-sizing:border-box;"
      + "background-color:#f4f4f4;"
      + "height:100%;"
      + "}"
      + ".jbi_summary_legend_item:not(:first-child){"
      + "border-left:1px solid lightgrey;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi_title{"
      + "font-family: " + fontFamily + ";"
      + "font-size: 12px;"
      + "line-height: " + summaryConfig["KpiHeightPixels"] + "px;"
      + "color: #505050;"
      + "text-transform: uppercase;"
      + "display: inline-block;"
      + "position: absolute;"
      + "left: 5px;"
      + "right: 0;"
      + "top: 0;"
      + "bottom: 0;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi_value{"
      + "display: inline-block;"
      + "position: absolute;"
      + "top: 0;"
      + "bottom: 0;"
      + "right: 5px;"
      + "font-size: 12px;"
      + "font-family: " + fontFamily + ";"
      + "line-height: " + summaryConfig["KpiHeightPixels"] + "px;"
      + "background-color: white;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi_value i{"
      + "font-weight: normal;"
      + "line-height: " + summaryConfig["KpiHeightPixels"] + "px;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi_value span{"
      + "line-height: " + summaryConfig["KpiHeightPixels"] + "px;"
      + "vertical-align: top;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi_value_negative{"
      + "color: #1491B8;"
      + "}"
      + "#jbi_summary_kpi .jbi_summary_kpi_value_negative i{"
      + "transform: rotate(135deg);"
      + "}"
      + "#jbi_summary_filters{"
      + "display: block;"
      + "color: white;"
      + "font-size: 12px;"
      + "font-family: " + fontFamily + ";"
      + "text-align: center;"
      + "width: " + filtersWidthPixels + "px;"
      + "line-height: " + summaryConfig["FiltersHeightPixels"] + "px;"
      + "text-transform: uppercase;"
      + "list-style: none;"
      + "margin: 0;"
      + "padding: 0;"
      + "z-index: 99;"
      + "margin-left: auto;"
      + "margin-right: auto;"
      + "cursor: pointer;"
      + "}";
    if (!my.isMobile) {
      s += "#jbi_summary_filters:hover{"
        + "background-color: " + summaryConfig["BackgroundFilterHoverColor"] + ";"
        + "-webkit-transition: background-color 200ms ease-in-out;"
        + "-moz-transition: background-color 200ms ease-in-out;"
        + "-o-transition: background-color 200ms ease-in-out;"
        + "transition: background-color 200ms ease-in-out;"
        + "}"
        + ".jbi_summary_filter_value:hover{"
        + "background-color: #628593;"
        + "-webkit-transition: background-color 200ms ease-in-out;"
        + "-moz-transition: background-color 200ms ease-in-out;"
        + "-o-transition: background-color 200ms ease-in-out;"
        + "transition: background-color 200ms ease-in-out;"
        + "}"
        + "#jbi_summary_filter_business_items li:hover{"
        + "background-color: " + summaryConfig["BackgroundFilterHoverColor"] + ";"
        + "-webkit-transition: background-color 200ms ease-in-out;"
        + "-moz-transition: background-color 200ms ease-in-out;"
        + "-o-transition: background-color 200ms ease-in-out;"
        + "transition: background-color 200ms ease-in-out;"
        + "}";
    }
    s += "#jbi_summary_filter_business_items{"
      + "display: none;"
      + "color: #505050;;"
      + "font-size: 12px;"
      + "box-sizing: border-box;"
      + "font-family: " + fontFamily + ";"
      + "background-color: white;"
      + "text-align: left;"
      + "width: " + filtersWidthPixels + "px;"
      + "line-height: " + summaryConfig["FiltersHeightPixels"] + "px;"
      + "text-transform: uppercase;"
      + "font-weight: bold;"
      + "list-style: none;"
      + "margin: 0;"
      + "margin-left: -1px;"
      + "padding: 0;"
      + "position: absolute;"
      + "z-index: 99;"
      + "border: 1px solid lightgrey;"
      + "}"
      + ".jbi_summary_filter_value{"
      + "padding-left: 5px;"
      + "line-height: 40px;"
      + "background-color: white;"
      + "}"
      + ".jbi_summary_filter_active{"
      + "background-color: #E7EFF3;"
      + "}"
      + ".jbi_summary_kpi_trend_icon{"
      + "width:24px;"
      + "margin-top:-2px;"
      + "padding-right:4px;"
      + "vertical-align:middle;"
      + "}"
      + ".jbi_summary_kpi_value span.jbi_summary_tooltip {"
      + "display: none;"
      + "position: absolute;"
      + "top: 36px;"
      + "right: -15px;"
      + "padding: 5px;"
      + "z-index: 100;"
      + "background: #ffffff;"
      + "color: #555555;"
      + "border: 1px solid #8f8f8f;"
      + "box-shadow: 1px 1px 1px #888888;"
      + "border-radius: 5px;"
      + "}"
      + ".jbi_summary_kpi_value:hover span.jbi_summary_tooltip {"
      + "display: block;"
      + "}"
      + ".jbi_summary_tooltip:before {"
      + "content: '';"
      + "display: block;"
      + "position: absolute;"
      + "width: 0;"
      + "height: 0;"
      + "right: 38px;"
      + "top: -9px;"
      + "border-left: 6px solid transparent;"
      + "border-right: 6px solid transparent;"
      + "border-bottom: 9px solid #8f8f8f;"
      + "}"
      + ".jbi_summary_tooltip > table {"
      + "font-size: 10px;"
      + "font-weight: normal;"
      + "line-height: 14px;"
      + "width: 100%;"
      + "white-space: nowrap;"
      + "}"
      + ".jbi_summary_tooltip_value{"
      + "text-align: right;"
      + "padding-left: 15px;"
      + "}"

      + ".jbi_summary_chart{"
      + "position: absolute;"
      + "left : 0;"
      + "right : 0;"
      + "top : 0;"
      + "bottom : 5px;"
      + "overflow: hidden;"
      + "}"
      + ".jbi_summary_chart ToggleSeriesButton.ToggleSeriesButton{"
      + "right: 2px;"
      + "bottom: 2px;"
      + "width: 100px;"
      + "height: 20px;"
      + "line-height: 20px;"
      + "position: absolute;"
      + "float: right;"
      + "font-size: 10px;"
      + "font-family: " + fontFamily + ";"
      + "cursor: pointer;"
      + "text-align: center;"
      + "background-color: #EEE;"
      + "color: #666;"
      + "}";
    if (!my.isMobile) {
      s += ".jbi_summary_chart ToggleSeriesButton.ToggleSeriesButton:hover{"
        + "background-color: #D8D8D8;"
        + "}";
    }

    // Static reports section
    s += "#jbi_reports{"
      + "position: relative;"
      + "display:block;"
      + "left: 0;"
      + "right: 0;"
      + "top: " + (reportConfig["TopPixels"] || 0) + "px;"
      + "background-color : white;"
      + "}"
      + "#jbi_reports_published {"
      + "position: relative;"
      + "display: block;"
      + "left: 0;"
      + "right: 0;"
      + "top: 30px;"
      + "background-color: white;"
      + "}"
      + ".jbi_reports_title{"
      + "margin-top: 5px;"
      + "margin-left: 7px;"
      + "font-size: 16px;"
      + "color: #32323A;"
      + "font-family: Futura, 'Trebuchet MS', Arial, sans-serif;"
      + "font-weight: bold;"
      + "text-transform: uppercase;"
      + "}"
      + ".jbi_reports_item table {"
      + "text-transform: initial !important;"
      + "font-weight: normal;"
      + "font-size: 11px;"
      + "font-family: " + fontFamily + ";"
      + "}"
      + ".jbi_reports_item td {"
      + "padding: 5px;"
      + "}"
      + ".jbi_reports_item th {"
      + "padding: 2px 5px 2px 5px;"
      + "}"
      + ".jbi_reports_items{"
      + "list-style: none;"
      + "display: block;"
      + "margin: 0px;"
      + "margin-left: 5px;"
      + "margin-right: 5px;"
      + "padding: 0px;"
      + "}"
      + ".jbi_reports_items li{"
      + "display: inline-block;";

    // if (my.isMobile) {
    //   s += "min-width: 160px;"
    // } else {
      s += "width: 20%;";
    // }
    s += "padding: 0px;"
      + "margin: 0px;"
      + "vertical-align: top;"
      + "}"
      + ".jbi_reports_item{"
      + "position: relative;"
      + "font-size: 15px;"
      + "border: 1px solid #EFEFEF;"
      + "border-radius: 5px;"
      + "color: black;"
      + "font-family: " + fontFamily + ";"
      + "font-weight: normal;"
      + "margin: 5px;"
      + "height: 200px;"
      + "background-color: white;"
      + "}"
      + ".jbi_reports_item.jbi_report.active{"
      + "cursor: pointer;"
      + "}"
        //+ ".jbi_header_report.jbi_report.online{"
        //  + "background-color: #00576d;"
        //  + "border: 1px solid #0090B6;"
        //  + "color: white;"
        //  + "opacity: 1!important;"
        //  + "cursor: pointer;"
        //+ "}"
      + ".jbi_header_report.jbi_report.online span{"
      + "opacity: 1!important;"
      + "}";

    if (!my.isMobile) {
      s += ".jbi_reports_item.jbi_report.active:hover{"
        + "background-color: #dcdcdc;"
        + "-webkit-transition: background-color 200ms ease-in-out;"
        + "-moz-transition: background-color 200ms ease-in-out;"
        + "-o-transition: background-color 200ms ease-in-out;"
        + "transition: background-color 200ms ease-in-out;"
        + "}";
    }

    s += ".jbi_reports_item_clicker{"
      + "text-align: center;"
      + "color: #32323A;"
      + "font-family: Futura, 'Trebuchet MS', Arial, sans-serif;"
      + "height: 38px;"
      + "position: absolute;"
      + "left: 0;"
      + "right: 0;"
      + "bottom: 0;"
      + "background-color: #007fa0;"
      + "}"
      + ".jbi_reports_icon {"
      + "text-align: center; "
      + "margin-top: 10px; "
      + "height: 90px;"
      + "}"
        + ".jbi_reports_nodata_table{"
        + "display:table;"
    + "width:100%;"
    + "margin-top:40px;"
        + "}"

        + ".jbi_reports_nodata_div {"
        + "display:table-cell;"
    + "vertical-align:middle;"
      + "text-align:center;"
    + "font-size:11px;"
    + "font-family:Futura,\'Trebuchet MS\', Arial, sans-serif;"
        + "}"
        + ".jbi_text_left {"
        + " text-align: left;"
        + "}"
        + ".jbi_text_right {"
        + "  text-align: right;"
        + "}"
        + ".jbi_tablerow_border_top {"
        + "border-top: solid 1px #d8d8d8;"
        + "}"
        + ".jbi_reports_table_background {"
        + " background-color: #f7d753"
        + "}"
        + ".jbi_reports_data_table{"
        + "border-spacing: 0;"
        + "width: 100%;"
        + "margin-top: 10px;"
        + "}"
      + ".jbi_reports_name{"
      + "padding-left: 5px;"
      + "padding-right: 5px;"
      + "text-align: center;"
      + "padding-top: 3px;"
      + "font-family: " + fontFamily + ";"
      + "text-transform: initial !important;"
      + "font-weight: normal;";

    if (!my.isMobile) {
      s += "font-size: 15px;";
    } else {
      s += "font-size: 10px;";
    }

    s += "overflow: hidden;"
      + "text-overflow: ellipsis;"
      + "white-space: nowrap;"
      + "}"
      + ".jbi_reports_details{"
      + "text-transform: initial;"
      + "font-weight: normal;"
      + "padding-left: 5px;"
      + "font-family: Futura, 'Trebuchet MS', Arial, sans-serif;"
      + "font-size: 11px;"
      + "overflow: hidden;"
      + "text-overflow: ellipsis;"
      + "white-space: nowrap;"
      + "}"




        // Static trend section
      + "#jbi_trend{"
      + "position: relative;"
      + "display: block;"
      + "margin-top: 24px;"
      + "background-color: " + trendConfig["BackgroundColor"] + ";"
      + "left: 0;"
      + "right: 0;";
    if (my.isMobile) {
      s += "height: 170px;";
    } else {
      s += "height:" + trendConfig["HeightPixels"] + "px;";
    }
    s += "}"
      + "#jbi_trend_chart{"
      + "position: absolute;"
      + "top: 25px;";
    if (my.isMobile) {
      s += "height: 170px;";
    } else {
      s += "height:" + trendConfig["HeightPixels"] + "px;";
    }
    s += "left: 0;"
      + "right: 0;"
      + "font-size: 0px;"
      + "}"
      + "#jbi_trend_chart .jbi_trend_chart{"
      + "position: relative;"
      + "width: 33.33%;";
    if (my.isMobile) {
      s += "height: 170px;";
    } else {
      s += "height:" + trendConfig["HeightPixels"] + "px;";
    }
    s += "display: inline-block;"
      + "}"
      + ".jbi_trend_chart_item{"
      + "position: absolute;"
      + "left: 0;"
      + "right: 0;"
      + "top: 0;"
      + "bottom: 0;"
      + "margin: 5px;"
      + "border: 1px solid #EFEFEF;"
      + "border-radius: 3px;"
      + "}";
    if (!my.isMobile) {
      s += ".jbi_trend_chart_item:hover{"
        + "background-color: " + trendConfig["BackgroundHoverColor"] + ";"
        + "-webkit-transition: background-color 200ms ease-in-out;"
        + "-moz-transition: background-color 200ms ease-in-out;"
        + "-o-transition: background-color 200ms ease-in-out;"
        + "transition: background-color 200ms ease-in-out;"
        + "}";
    }
    s += ".jbi_trend_chart_container{"
      + "position: absolute;"
      + "left: 0;"
      + "right: 0;"
      + "top: 30px;"
      + "bottom: 0;"
      + "}"
      + ".jbi_trend_chart_label{"
      + "position: absolute;"
      + "left: 0;"
      + "right: 0;"
      + "top: 0;"
      + "bottom: 0;"
      + "}"
      + ".jbi_trend_chart_title{"
      + "position: absolute;"
        //+ "background-color: #EFEFEF;"
      + "top: 0px;"
      + "left: 0;"
      + "right: 0;"
      + "height: 30px;"
      + "line-height: 30px;"
      + "text-align: center;"
      + "font-size: 15px;"
      + "font-family: " + fontFamily + ";"
      + "}"
      + ".jbi_trend_chart_value_left{"
      + "display: inline-block;"
      + "position: absolute;"
      + "top: 0;"
      + "bottom: 0;"
      + "left: 35px;"
      + "font-size: 12px;"
      + "font-family: " + fontFamily + ";"
      + "font-weight: bold;"
      + "line-height: 28px;"
      + "color: white;"
      + "padding-top: 2px;"
      + "}"
      + ".jbi_trend_chart_value_right{"
      + "display: inline-block;"
      + "position: absolute;"
      + "top: 0;"
      + "bottom: 0;"
      + "right: 5px;"
      + "font-size: 12px;"
      + "font-family: " + fontFamily + ";"
      + "font-weight: bold;"
      + "line-height: 28px;"
      + "color: white;"
      + "padding-top: 2px;"
      + "}"
      + ".jbi_trend_chart_value_left i{"
      + "font-weight: normal;"
      + "line-height: 28px;"
      + "}"
      + ".jbi_trend_chart_value_right i{"
      + "font-weight: normal;"
      + "line-height: 28px;"
      + "}"
      + ".jbi_trend_chart_value_right span{"
      + "font-weight: bold;"
      + "line-height: 28px;"
      + "vertical-align: top;"
      + "}"
      + ".jbi_trend_chart_value_left span{"
      + "font-weight: bold;"
      + "line-height: 28px;"
      + "vertical-align: top;"
      + "}"
      + ".jbi_trend_chart_value_negative i{"
      + "transform: rotate(135deg);"
      + "}"
      + ".jbi_trend_chart_value_left span.jbi_trend_tooltip {"
      + "display: none;"
      + "position: absolute;"
      + "top: -72px;"
      + "right: -15px;"
      + "padding: 5px;"
      + "z-index: 100;"
      + "background: #ffffff;"
      + "color: #555555;"
      + "border: 1px solid #8f8f8f;"
      + "box-shadow: 1px 1px 1px #888888;"
      + "border-radius: 5px;"
      + "}"
      + ".jbi_trend_chart_value_right span.jbi_trend_tooltip {"
      + "display: none;"
      + "position: absolute;"
      + "top: -72px;"
      + "right: -15px;"
      + "padding: 5px;"
      + "z-index: 100;"
      + "background: #ffffff;"
      + "color: #555555;"
      + "border: 1px solid #8f8f8f;"
      + "box-shadow: 1px 1px 1px #888888;"
      + "border-radius: 5px;"
      + "}"
      + ".jbi_trend_chart_value_left:hover span.jbi_trend_tooltip {"
      + "display: block;"
      + "}"
      + ".jbi_trend_chart_value_right:hover span.jbi_trend_tooltip {"
      + "display: block;"
      + "}"
      + ".jbi_trend_tooltip:before {"
      + "content: '';"
      + "display: block;"
      + "position: absolute;"
      + "width: 0;"
      + "height: 0;"
      + "right: 38px;"
      + "bottom: -9px;"
      + "border-left: 6px solid transparent;"
      + "border-right: 6px solid transparent;"
      + "border-top: 9px solid #8f8f8f;"
      + "}"
      + ".jbi_trend_tooltip > table {"
      + "font-size: 10px;"
      + "font-weight: normal;"
      + "line-height: 14px;"
      + "width: 100%;"
      + "white-space: nowrap;"
      + "}"
      + ".jbi_trend_tooltip_value{"
      + "text-align: right;"
      + "padding-left: 15px;"
      + "}"

      + "#jbi_trend_chart .message-placeholder{"
      + "  display: table;"
      + "  width: 100%;"
      + "  height: 100%;"
      + "  min-height: 100px;"
      + "  border: 1px solid #EFEFEF;"
      + "  border-radius: 5px;"
      + "}"
      + "#jbi_trend_chart .message-placeholder .message{"
      + "  display:table-cell;"
      + "  vertical-align: middle;"
      + "  font-family: " + fontFamily + ";"
      + "  font-size: 11px;"
      + "  text-align: center;"
      + "  color: black;"
      + "}";
//@formatter:on
    s += "</style>";

    // Add the CSS to the head of the HTML page
    $(s).appendTo("head");


    // HELPER FUNCTIONS

    function getConfigStyle() {
      var customConfig = $("body").data("customConfig");
      if (!customConfig
        || !customConfig["CONFIG"]) {
        return null;
      }
      return customConfig["CONFIG"];
    }

  };


  return my;

}(shell.app.execdblp.dashboard));
